[package]
name = "bench-getundo"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.6"
bitcoin_slices = { version = "0.10.0", features = ["bitcoin"] }
clap = { version = "4.5.39", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
ureq = "3.0.11"
